import type { DetailForm } from "./types";

export const ARTIST_ROLE_OPTIONS = [
  { id: "1", label: "Penciller" },
  { id: "3", label: "Colorist" },
  { id: "5", label: "Inker" },
  { id: "6", label: "All" },
  { id: "7", label: "Painter" },
  { id: "8", label: "Layouts" },
  { id: "9", label: "Finisher" },
  { id: "10", label: "Assistant" },
  { id: "11", label: "Letterer" },
  { id: "12", label: "Writer" },
  { id: "13", label: "Restorer" },
];

export const MEDIA_TYPE_OPTIONS = [
  { id: "12", label: "Colored Pencils" },
  { id: "11", label: "Computer Art" },
  { id: "1", label: "Ink Wash" },
  { id: "2", label: "Marker" },
  { id: "3", label: "Mixed Media" },
  { id: "4", label: "Paint - Acrylic" },
  { id: "5", label: "Paint - Oil" },
  { id: "6", label: "Paint - Watercolor" },
  { id: "13", label: "Pastels" },
  { id: "7", label: "Pen and Ink" },
  { id: "8", label: "Pencil" },
  { id: "9", label: "Photograph" },
];

export const ART_TYPE_OPTIONS = [
  { id: "18", label: "Animation" },
  { id: "16", label: "Color Guide" },
  { id: "10", label: "Comic Strip" },
  { id: "2", label: "Commission" },
  { id: "21", label: "Complete Story" },
  { id: "8", label: "Convention Sketch" },
  { id: "1", label: "Cover" },
  { id: "12", label: "Double Page Splash" },
  { id: "13", label: "Double Page Spread" },
  { id: "23", label: "Illustration" },
  { id: "3", label: "Interior Page" },
  { id: "25", label: "Mystery Sketch" },
  { id: "26", label: "Mystery Sketch Card" },
  { id: "5", label: "Other" },
  { id: "22", label: "Partial Story" },
  { id: "20", label: "Photograph" },
  { id: "6", label: "Pin Up" },
  { id: "9", label: "Prelim" },
  { id: "14", label: "Recreation" },
  { id: "15", label: "Remarked Item" },
  { id: "11", label: "Sketch Card" },
  { id: "24", label: "Sketch Cover" },
  { id: "7", label: "Sketchbook" },
  { id: "4", label: "Splash Page" },
  { id: "17", label: "Title Page" },
  { id: "19", label: "Trading Card Art" },
];

export const PUBLICATION_STATUS_OPTIONS = [
  { id: "2", label: "Unpublished Art" },
  { id: "1", label: "Published Art" },
  { id: "3", label: "CAF Member Art" },
];

export const SNIKT_ART_TYPE_OPTIONS = [
  "Cover",
  "Interior",
  "Commission",
  "Trading Card Art",
  "Animation Cel",
  "Comic Strip",
  "Other Illustration",
];

export const SNIKT_ANIMATION_SUBCATEGORY_OPTIONS = [
  "Production Cel",
  "Model Cel",
  "Promotional Cel",
  "Sericel",
  "Production Drawing",
  "Model/Design Drawing",
  "Concept Drawing",
  "Promotional Drawing",
  "Storyboard",
  "Background",
];

export const emptyForm: DetailForm = {
  title: "",
  description: "",
  forSaleStatus: "NFS",
  mediaTypeId: "7",
  artTypeId: "3",
  publicationStatusId: "2",
  active: true,
  illustrationExchange: false,
  ixForSale: false,
  artistCredits: [{ firstName: "", lastName: "", roleId: "" }],
  cafUrl: "",
  sniktUrl: "",
  raremarqUrl: "",
  genericUrl: "",
  sniktMetadata: {
    artType: "",
    comicPublisher: "",
    seriesTitle: "",
    issueNumber: "",
    seriesPageNumber: "",
    year: "",
    character: "",
    subcategory: "",
    animationStudio: "",
    episodeNumber: "",
    episodeTitle: "",
    publishedDate: "",
    stripTitle: "",
    isSundayStrip: false,
    other: "",
    tags: "",
    isNsfw: false,
    isForSale: false,
    price: "",
    isOpenToOffers: false,
  },
  purchasePrice: "",
  estimatedValue: "",
  purchaseDate: "",
  provenance: "",
  personalNotes: "",
};
